apply plugin: "application"

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.kotlin.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = ["../assets"]

application {
    mainClass = "com.mygdx.game.GameStart"
}

project.ext.assetsDir = new File("../assets")

import org.gradle.internal.os.OperatingSystem

// The "run" task is created by the application plugin; point it at the assets
// folder so the game finds its resources the same way it does when packaged.
tasks.named('run', JavaExec) {
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true

    if (OperatingSystem.current() == OperatingSystem.MAC_OS) {
        // Required to run on macOS
        jvmArgs += "-XstartOnFirstThread"
    }
}

tasks.register('debug', JavaExec) {
    dependsOn classes
    mainClass = application.mainClass
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true
    debug = true
}

tasks.register('dist', Jar) {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    with jar
}


dist.dependsOn classes

eclipse.project.name = appName + "-desktop"
